coverage:
  precision: 2
  round: nearest
  range: 60...100

  status:
    project:
      default:
        target: auto

    patch:
      default:
        target: auto

  ignore:
    - lib/spack/spack/test/.*
    - lib/spack/env/.*
    - lib/spack/docs/.*
    - lib/spack/external/.*

comment: off
